name: CI # Название пайплайна

on: # Триггер (Когда кто-то делает git push — запускай workflow.)
  push

jobs: # Создаем задачу

  test: # Сама задача
    runs-on: ubuntu-latest # Runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4